version: '2'

services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: verdaccio
    ports:
      - "8080:4873"
    volumes:
        - "./conf:/verdaccio/conf"

volumes:
  verdaccio:
    driver: local